### ISSUE TITLE
Intake - Step2 Page is always in English even if the rest of the application is in Spanish

### ISSUE THREAD

**Issue by ale90bsas** [mapplics/quarentime#8]
After filling the Personal Information page (and passing through the authentication if enabled) the Step 2 page is shown but in English when it should be in Spanish.

![image](https://user-images.githubusercontent.com/30640814/78194254-01d40080-7453-11ea-809b-d62d3e6d9e0d.png)

**Comment by mapplics** [comment]
this is because we don't have all the translations yet, and by default always show english @ale90bsas

**Comment by ale90bsas** [comment]
@mapplics who should we ask for completing that translation?

**Comment by mapplics** [comment]
@ale90bsas  I don't know, who can make it. We can do it in spanish, but we need germany, macedonian and deutch to. Maybe we need to find someone to do this job in a hurry, beacuse is very import. 
But first we need to be sure that the english text are in the final version

**Comment by ale90bsas** [comment]
@mapplics 

We can manually translate this one at least to Spanish, what do you think?
At least to unblock the testing in Spanish countries.

**Comment by mapplics** [comment]
yes but, first, we need to be sure that english texts are in the final version, maybe @pitu can confirm this. @ale90bsas
